### ISSUE TITLE
Is this using the right license?

### ISSUE THREAD

**Issue by rwthompsonii** [system76/libpci-sys#1]
My team believes this crate to be mis-licensed, or at the very least needs a strong disclaimer about its use.

> libpci-dev

That lib is GPLv2, which given this links directly to it, would cause this lib to also need a GPLv2 license.  

At best, you could argue that it's ok to build & link against a locally installed lib but as soon as you ship that to any other box it's a license violation.

As a result we're going to not use it, and wanted to warn others in case they're relying on cargo-license to catch things like this.

**Comment by jackpot51** [comment]
This is an incorrect understanding of the GPLv2 license. A program or other binary produced by dynamically linking libpci is not considered to be a derived work of libpci and is therefore not required to also be licensed GPLv2, see the README of https://github.com/pciutils/pciutils.

Even if it was, this does not mean that libpci-sys has to be licensed GPLv2. The GPLv2 license only requires that resulting binaries that include GPLv2 code are licensed in a compatible manner with the GPLv2 license.

**Comment by rwthompsonii** [comment]
> At best, you could argue that it's ok to build & link against a locally installed lib but as soon as you ship that to any other box it's a license violation.

**Comment by rwthompsonii** [comment]
That's not a fun surprise to someone that thinks "i can just check the license of all my crates" and be fine.  At the least, I believe a disclaimer would be courteous in a doc or something.

**Comment by jackpot51** [comment]
> That's not a fun surprise to someone that thinks "i can just check the license of all my crates" and be fine. At the least, I believe a disclaimer would be courteous in a doc or something.

If you believe such a thing would be helpful you can feel free to open a PR.
